[package]
org = "kumara"
name = "social_media_service"
version = "0.1.0"
distribution = "2201.10.1"

[build-options]
observabilityIncluded = true

[[tool.persist]]
id = "generate-db-client"
targetModule = "social_media_service"
options.datastore = "mysql"
filePath = "persist/model.bal"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.4.0"


